### ISSUE TITLE
Sort by sender

### ISSUE THREAD

**Issue by emilstahl** [olegam/Postboks#12]
Sort in sub folders by sender (Sender id)

**Comment by olegam** [comment]
How would you do that exactly? What would an example of the folder structure be? What if you have hundreds of documents from one sender? Would you prefer this folder structure instead of the current by-month structure? Or something involving sym-links? Or a native interface to browse documents in the app?

**Comment by emilstahl** [comment]
I guess I wasn’t clear enough.

Create a folder for each sender in the current month structure.

**Before**
<img width=“566” alt=“before” src="https://cloud.githubusercontent.com/assets/3885790/12128186/fc7795f0-b3fb-11e5-839a-e3a67fa5cb38.png">

**After**
<img width="466" alt="after" src="https://cloud.githubusercontent.com/assets/3885790/12128342/efeefeee-b3fc-11e5-91cb-c4a0a5533b63.png">

**Comment by olegam** [comment]
That makes sense... I mostly get documents from different senders each month. But that can of course be different for others.. Is it something you would like to try implementing yourself?

**Comment by olegam** [comment]
...to clarify: i'm probably not getting around to this any time soon but I can provide some guidance if you want to give it a go.

**Comment by boserup** [comment]
I added this as an option in #16
